-- =============================================================================
-- 04_online.sql
-- Purpose: Source 3, the online store.
-- Design ref: docs/Architecture_and_Data_Model.md section 4.3.
-- Prerequisites: 02_store_ops.sql (orders reserve stock through the store
--                system's reserve_stock interface).
-- Own identifiers: web_sku ('WEB-10001'), collection point code
--                  ('CP-PARRAMATTA'), order_no.
-- Outputs: product, online_stock (combined quantity, refreshed by the sync),
--          collection_point, postcode_location, web_order + web_order_line,
--          distance_km() and place_online_order() (multi-line and one-line).
-- =============================================================================

CREATE TABLE online.product (
    web_sku      text          NOT NULL,
    title        text          NOT NULL,
    web_price    numeric(10,2) NOT NULL,
    pos_barcode  text          NOT NULL,
    CONSTRAINT pk_online_product PRIMARY KEY (web_sku),
    CONSTRAINT ck_online_product_price CHECK (web_price >= 0)
);
COMMENT ON TABLE online.product IS 'Web catalogue. Titles are written for the website and differ from store descriptions.';
COMMENT ON COLUMN online.product.pos_barcode IS
'Barcode the store system needs when the website asks it to hold stock. Operational routing only; the warehouse does not use it for integration.';

CREATE TABLE online.online_stock (
    web_sku             text        NOT NULL,
    available_quantity  integer     NOT NULL DEFAULT 0,
    last_synced_at      timestamptz,
    CONSTRAINT pk_online_stock PRIMARY KEY (web_sku),
    CONSTRAINT fk_online_stock_product FOREIGN KEY (web_sku) REFERENCES online.product (web_sku),
    CONSTRAINT ck_online_stock_available CHECK (available_quantity >= 0)
);
COMMENT ON TABLE online.online_stock IS
'What the website shows: one combined quantity per product for all five stores. Lowered immediately by the website''s own reserved orders; otherwise only dw.run_sync() changes it, so in-store sales, deliveries and store-side cancellations leave it stale until the next sync.';

CREATE TABLE online.collection_point (
    cp_code     text         NOT NULL,
    cp_name     text         NOT NULL,
    latitude    numeric(9,6) NOT NULL,
    longitude   numeric(9,6) NOT NULL,
    store_no    text         NOT NULL,
    CONSTRAINT pk_collection_point PRIMARY KEY (cp_code)
);
COMMENT ON TABLE online.collection_point IS 'Click-and-collect pickup point; one per physical store.';
COMMENT ON COLUMN online.collection_point.store_no IS
'Store number used when calling the store system to hold stock. Operational routing only.';

CREATE TABLE online.postcode_location (
    postcode   text         NOT NULL,
    suburb     text         NOT NULL,
    latitude   numeric(9,6) NOT NULL,
    longitude  numeric(9,6) NOT NULL,
    CONSTRAINT pk_postcode_location PRIMARY KEY (postcode)
);
COMMENT ON TABLE online.postcode_location IS 'Approximate centre of each customer postcode, used to rank collection points by distance.';

CREATE TABLE online.web_order (
    order_no           bigint      GENERATED BY DEFAULT AS IDENTITY,
    customer_postcode  text        NOT NULL,
    pickup_cp_code     text        NOT NULL,
    status             text        NOT NULL,
    ordered_at         timestamptz NOT NULL,
    CONSTRAINT pk_web_order PRIMARY KEY (order_no),
    CONSTRAINT fk_web_order_postcode FOREIGN KEY (customer_postcode) REFERENCES online.postcode_location (postcode),
    CONSTRAINT fk_web_order_pickup FOREIGN KEY (pickup_cp_code) REFERENCES online.collection_point (cp_code),
    CONSTRAINT ck_web_order_status CHECK (status IN ('reserved', 'partial_shortfall', 'shortfall', 'rejected'))
);
COMMENT ON TABLE online.web_order IS
'One online click-and-collect order (header). The customer collects everything at pickup_cp_code, the collection point closest to their postcode. status: reserved = every line held; partial_shortfall = some lines could not be supplied; shortfall = no line could; rejected = the website number did not cover every line, nothing held.';

CREATE TABLE online.web_order_line (
    order_no              bigint  NOT NULL,
    line_no               integer NOT NULL,
    web_sku               text    NOT NULL,
    quantity              integer NOT NULL,
    online_qty_shown      integer NOT NULL,
    source_cp_code        text,
    store_reservation_no  bigint,
    line_status           text    NOT NULL,
    CONSTRAINT pk_web_order_line PRIMARY KEY (order_no, line_no),
    CONSTRAINT uq_web_order_line_sku UNIQUE (order_no, web_sku),
    CONSTRAINT fk_web_order_line_order FOREIGN KEY (order_no) REFERENCES online.web_order (order_no),
    CONSTRAINT fk_web_order_line_product FOREIGN KEY (web_sku) REFERENCES online.product (web_sku),
    CONSTRAINT fk_web_order_line_source FOREIGN KEY (source_cp_code) REFERENCES online.collection_point (cp_code),
    CONSTRAINT ck_web_order_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_web_order_line_status CHECK (line_status IN ('reserved', 'shortfall', 'rejected')),
    CONSTRAINT ck_web_order_line_source CHECK ((line_status = 'reserved') = (source_cp_code IS NOT NULL AND store_reservation_no IS NOT NULL))
);
COMMENT ON TABLE online.web_order_line IS
'One product on an online order. reserved = held at source_cp_code (the pickup store itself, or another store that transfers it to the pickup store); shortfall = no single store had the whole quantity; rejected = the order was rejected.';
COMMENT ON COLUMN online.web_order_line.online_qty_shown IS 'online_stock.available_quantity for this product when the order was placed (possibly stale).';
COMMENT ON COLUMN online.web_order_line.source_cp_code IS 'Store the units were taken from. Different from the order''s pickup_cp_code when the line is transferred.';

-- Great-circle distance in kilometres between two points (haversine).
CREATE FUNCTION online.distance_km(lat1 numeric, lon1 numeric, lat2 numeric, lon2 numeric)
RETURNS numeric LANGUAGE sql IMMUTABLE AS $$
    SELECT (2 * 6371 * asin(sqrt(
               power(sin(radians(lat2 - lat1) / 2), 2)
             + cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lon2 - lon1) / 2), 2)
           )))::numeric(10,2);
$$;

-- Place an online click-and-collect order with one or more lines.
--   1. Pickup store = the collection point closest to the customer's postcode.
--   2. The website accepts the order only if ITS OWN (possibly stale) number
--      covers every line; otherwise the whole order is rejected.
--   3. For each line, ask the store system to hold the REAL stock: first at
--      the pickup store; if it lacks the whole quantity, at the next-nearest
--      store that has it (that store will transfer it to the pickup store).
--      A line is never split across stores.
--   4. A line no store can supply is a shortfall; the other lines still go ahead.
--   5. Reserved lines lower the website number at once (the website knows its
--      own sales). Shortfall and rejected lines took no stock.
-- Example: SELECT online.place_online_order('2026', ARRAY['WEB-10003','WEB-10013'], ARRAY[2,2]);
-- p_ordered_at lets the seed script record past orders.
CREATE FUNCTION online.place_online_order(
    p_postcode    text,
    p_web_skus    text[],
    p_quantities  integer[],
    p_ordered_at  timestamptz DEFAULT now()
) RETURNS bigint
LANGUAGE plpgsql AS $$
DECLARE
    v_lat          numeric;
    v_lon          numeric;
    v_order_no     bigint;
    v_pickup_cp    text;
    v_pickup_store text;
    v_rejected     boolean;
    v_line         record;
    v_cp           record;
    v_res_no       bigint;
    v_source_cp    text;
    v_reserved     integer := 0;
    v_short        integer := 0;
BEGIN
    IF coalesce(array_length(p_web_skus, 1), 0) = 0
       OR array_length(p_web_skus, 1) <> coalesce(array_length(p_quantities, 1), 0) THEN
        RAISE EXCEPTION 'Give one quantity per web SKU';
    END IF;
    IF EXISTS (SELECT 1 FROM unnest(p_quantities) AS q WHERE q IS NULL OR q <= 0) THEN
        RAISE EXCEPTION 'Quantities must be positive';
    END IF;
    IF (SELECT count(DISTINCT s) FROM unnest(p_web_skus) AS s) <> array_length(p_web_skus, 1) THEN
        RAISE EXCEPTION 'Each web SKU may appear only once per order';
    END IF;
    IF EXISTS (SELECT 1 FROM unnest(p_web_skus) AS s
                WHERE NOT EXISTS (SELECT 1 FROM online.product p WHERE p.web_sku = s)) THEN
        RAISE EXCEPTION 'Unknown web SKU in %', p_web_skus;
    END IF;

    SELECT latitude, longitude INTO v_lat, v_lon
      FROM online.postcode_location WHERE postcode = p_postcode;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unknown postcode %', p_postcode;
    END IF;

    -- 1. Pickup store: closest collection point.
    SELECT cp_code, store_no INTO v_pickup_cp, v_pickup_store
      FROM online.collection_point
     ORDER BY online.distance_km(v_lat, v_lon, latitude, longitude), cp_code
     LIMIT 1;

    -- Lock the website numbers so two orders cannot both be accepted on them.
    PERFORM 1 FROM online.online_stock WHERE web_sku = ANY (p_web_skus) ORDER BY web_sku FOR UPDATE;

    -- 2. Website check: every line must be covered by the website number.
    SELECT bool_or(coalesce(s.available_quantity, 0) < i.quantity) INTO v_rejected
      FROM unnest(p_web_skus, p_quantities) AS i (web_sku, quantity)
      LEFT JOIN online.online_stock s ON s.web_sku = i.web_sku;

    v_order_no := nextval(pg_get_serial_sequence('online.web_order', 'order_no'));
    INSERT INTO online.web_order (order_no, customer_postcode, pickup_cp_code, status, ordered_at)
    VALUES (v_order_no, p_postcode, v_pickup_cp, CASE WHEN v_rejected THEN 'rejected' ELSE 'reserved' END, p_ordered_at);

    FOR v_line IN
        SELECT i.n::integer AS line_no, i.web_sku, i.quantity, p.pos_barcode,
               coalesce(s.available_quantity, 0) AS shown
          FROM unnest(p_web_skus, p_quantities) WITH ORDINALITY AS i (web_sku, quantity, n)
          JOIN online.product p ON p.web_sku = i.web_sku
          LEFT JOIN online.online_stock s ON s.web_sku = i.web_sku
         ORDER BY i.n
    LOOP
        v_res_no := NULL;
        v_source_cp := NULL;

        IF NOT v_rejected THEN
            -- 3. Pickup store first, then the next-nearest stores.
            FOR v_cp IN
                SELECT cp.cp_code, cp.store_no
                  FROM online.collection_point cp
                 ORDER BY cp.cp_code <> v_pickup_cp,
                          online.distance_km(v_lat, v_lon, cp.latitude, cp.longitude), cp.cp_code
            LOOP
                v_res_no := store_ops.reserve_stock(v_cp.store_no, v_line.pos_barcode, v_line.quantity,
                                                    v_order_no::text, v_line.line_no,
                                                    v_pickup_store, p_ordered_at);
                IF v_res_no IS NOT NULL THEN
                    v_source_cp := v_cp.cp_code;
                    EXIT;
                END IF;
            END LOOP;

            IF v_res_no IS NOT NULL THEN
                -- 5. The website deducts its own reserved sale immediately.
                UPDATE online.online_stock
                   SET available_quantity = available_quantity - v_line.quantity
                 WHERE web_sku = v_line.web_sku;
                v_reserved := v_reserved + 1;
            ELSE
                v_short := v_short + 1;
            END IF;
        END IF;

        INSERT INTO online.web_order_line
            (order_no, line_no, web_sku, quantity, online_qty_shown, source_cp_code, store_reservation_no, line_status)
        VALUES
            (v_order_no, v_line.line_no, v_line.web_sku, v_line.quantity, v_line.shown, v_source_cp, v_res_no,
             CASE WHEN v_rejected THEN 'rejected' WHEN v_res_no IS NULL THEN 'shortfall' ELSE 'reserved' END);
    END LOOP;

    IF NOT v_rejected AND v_short > 0 THEN
        UPDATE online.web_order
           SET status = CASE WHEN v_reserved = 0 THEN 'shortfall' ELSE 'partial_shortfall' END
         WHERE order_no = v_order_no;
    END IF;

    RETURN v_order_no;
END;
$$;

-- Convenience for a one-product order.
-- Example: SELECT online.place_online_order('2026', 'WEB-10001', 2);
CREATE FUNCTION online.place_online_order(
    p_postcode    text,
    p_web_sku     text,
    p_quantity    integer,
    p_ordered_at  timestamptz DEFAULT now()
) RETURNS bigint
LANGUAGE sql AS $$
    SELECT online.place_online_order(p_postcode, ARRAY[p_web_sku], ARRAY[p_quantity], p_ordered_at);
$$;
